import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface BrandingOptions {
  logoUrl?: string;
  reportTitle?: string;
  reportFooter?: string;
  primaryColor?: string;
}

interface ExportVerdictOptions {
  userPrompt: string;
  synthesis: string;
  confidenceScore?: number;
  modelA: string;
  modelB: string;
  draftA: string;
  draftB: string;
  branding?: BrandingOptions;
}

export const exportVerdictToPDF = ({
  userPrompt,
  synthesis,
  confidenceScore,
  modelA,
  modelB,
  draftA,
  draftB,
  branding
}: ExportVerdictOptions, returnBase64 = false): string | void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Helper function to convert hex to RGB
  const hexToRgb = (hex: string) => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : { r: 0, g: 113, b: 227 }; // Default blue
  };

  const addHeader = (startY: number) => {
    // Header background with primary color (use branding color if provided)
    const headerColor = branding?.primaryColor || '#0071E3';
    const rgb = hexToRgb(headerColor);
    doc.setFillColor(rgb.r, rgb.g, rgb.b);
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Logo (use branding logo if provided)
    if (branding?.logoUrl) {
      try {
        // Note: For production, you'd need to convert the logo URL to base64
        // For now, we'll just show the title
        doc.setFontSize(24);
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.text(branding.reportTitle || "Audit Report", 20, 25);
      } catch (err) {
        console.error("Failed to load logo:", err);
        doc.setFontSize(24);
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.text(branding.reportTitle || "Audit Report", 20, 25);
      }
    } else {
      // Default title
      doc.setFontSize(24);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(branding?.reportTitle || "Genau Audit Report", 20, 25);
    }

    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(new Date().toLocaleString(), 20, 32);

    return 50; // Start Y position after header
  };

  const addFooter = (pageNum: number) => {
    const footerY = pageHeight - 15;
    
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(branding?.reportFooter || "Generated by Genau AI", 20, footerY);
    doc.text(`Page ${pageNum}`, pageWidth - 20, footerY, { align: 'right' });
  };

  // Initialize first page
  let currentY = addHeader(0);
  let pageNum = 1;
  addFooter(pageNum);

  // User Prompt Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text("Question Audited", 20, currentY);
  currentY += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const promptLines = doc.splitTextToSize(userPrompt, pageWidth - 40);
  promptLines.forEach((line: string) => {
    if (currentY > pageHeight - 30) {
      doc.addPage();
      pageNum++;
      currentY = 20;
      addFooter(pageNum);
    }
    doc.text(line, 20, currentY);
    currentY += 6;
  });

  currentY += 10;

  // Confidence Score Section
  if (confidenceScore !== undefined) {
    if (currentY > pageHeight - 40) {
      doc.addPage();
      pageNum++;
      currentY = 20;
      addFooter(pageNum);
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Confidence Score", 20, currentY);
    currentY += 8;

    doc.setFontSize(24);
    const headerColor = branding?.primaryColor || '#0071E3';
    const rgb = hexToRgb(headerColor);
    doc.setTextColor(rgb.r, rgb.g, rgb.b);
    doc.text(`${confidenceScore}%`, 20, currentY);
    doc.setTextColor(0, 0, 0);
    currentY += 15;
  }

  // Synthesis Section
  if (currentY > pageHeight - 50) {
    doc.addPage();
    pageNum++;
    currentY = 20;
    addFooter(pageNum);
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("The Council's Verdict", 20, currentY);
  currentY += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const synthesisLines = doc.splitTextToSize(synthesis, pageWidth - 40);
  synthesisLines.forEach((line: string) => {
    if (currentY > pageHeight - 30) {
      doc.addPage();
      pageNum++;
      currentY = 20;
      addFooter(pageNum);
    }
    doc.text(line, 20, currentY);
    currentY += 6;
  });

  currentY += 15;

  // Model A Draft
  if (currentY > pageHeight - 50) {
    doc.addPage();
    pageNum++;
    currentY = 20;
    addFooter(pageNum);
  }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Draft A (${modelA})`, 20, currentY);
  currentY += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const draftALines = doc.splitTextToSize(draftA.substring(0, 500) + "...", pageWidth - 40);
  draftALines.forEach((line: string) => {
    if (currentY > pageHeight - 30) {
      doc.addPage();
      pageNum++;
      currentY = 20;
      addFooter(pageNum);
    }
    doc.text(line, 20, currentY);
    currentY += 5;
  });

  currentY += 12;

  // Model B Draft
  if (currentY > pageHeight - 50) {
    doc.addPage();
    pageNum++;
    currentY = 20;
    addFooter(pageNum);
  }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Draft B (${modelB})`, 20, currentY);
  currentY += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const draftBLines = doc.splitTextToSize(draftB.substring(0, 500) + "...", pageWidth - 40);
  draftBLines.forEach((line: string) => {
    if (currentY > pageHeight - 30) {
      doc.addPage();
      pageNum++;
      currentY = 20;
      addFooter(pageNum);
    }
    doc.text(line, 20, currentY);
    currentY += 5;
  });

  // Save PDF or return base64
  if (returnBase64) {
    return doc.output('datauristring').split(',')[1];
  }
  
  const filename = `genau-audit-report-${new Date().getTime()}.pdf`;
  doc.save(filename);
};
