import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface ExportVerdictOptions {
  verdict: string;
  confidence?: number;
  userPrompt: string;
  drafts?: Array<{ agentName: string; role: string; content: string }>;
  timestamp: string;
}

export const exportVerdictToPDF = ({
  verdict,
  confidence,
  userPrompt,
  drafts,
  timestamp
}: ExportVerdictOptions, returnBase64 = false) => {
  const doc = new jsPDF();
  
  // Branding Header
  doc.setFillColor(6, 182, 212); // Teal accent
  doc.rect(0, 0, 210, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Consensus Report', 20, 20);
  
  // Timestamp
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(timestamp, 20, 26);
  
  let yPosition = 45;
  
  // User Prompt Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('User Query', 20, yPosition);
  yPosition += 7;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const promptLines = doc.splitTextToSize(userPrompt, 170);
  doc.text(promptLines, 20, yPosition);
  yPosition += promptLines.length * 5 + 10;
  
  // Confidence Score (if available)
  if (confidence !== undefined) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Confidence Score', 20, yPosition);
    yPosition += 7;
    
    doc.setFontSize(14);
    doc.setTextColor(6, 182, 212);
    doc.text(`${confidence}%`, 20, yPosition);
    doc.setTextColor(0, 0, 0);
    yPosition += 12;
  }
  
  // Council Verdict Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("The Council's Verdict", 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const verdictLines = doc.splitTextToSize(verdict, 170);
  
  verdictLines.forEach((line: string) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    doc.text(line, 20, yPosition);
    yPosition += 5;
  });
  
  // Draft Responses Section (if available)
  if (drafts && drafts.length > 0) {
    yPosition += 10;
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Council Member Responses', 20, yPosition);
    yPosition += 10;
    
    drafts.forEach((draft) => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`${draft.role} (${draft.agentName})`, 20, yPosition);
      yPosition += 7;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const draftLines = doc.splitTextToSize(draft.content.substring(0, 500) + '...', 170);
      doc.text(draftLines, 20, yPosition);
      yPosition += draftLines.length * 4 + 8;
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by Consensus Engine`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }
  
  // Return base64 or download
  if (returnBase64) {
    return doc.output('datauristring').split(',')[1];
  }
  
  const filename = `consensus-report-${new Date().getTime()}.pdf`;
  doc.save(filename);
};
