import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table";
import { Popover, PopoverContent, PopoverTrigger } from "./ui/popover";
import { Calendar } from "./ui/calendar";
import { FileDown, FileText, CalendarIcon } from "lucide-react";
import { format, subDays, startOfMonth } from "date-fns";
import { toast } from "sonner";
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { useState } from "react";
import { cn } from "@/lib/utils";

interface Transaction {
  id: string;
  user_id: string;
  amount: number;
  balance_after: number;
  created_at: string;
  description: string | null;
  transaction_type: string;
  model_used: string | null;
}

export const BillingTransactionsPanel = () => {
  const [dateRange, setDateRange] = useState<{ from: Date; to: Date }>({
    from: subDays(new Date(), 30),
    to: new Date(),
  });

  const { data: transactions, isLoading } = useQuery({
    queryKey: ['admin-billing-transactions', dateRange],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('billing_transactions')
        .select('*')
        .gte('created_at', dateRange.from.toISOString())
        .lte('created_at', dateRange.to.toISOString())
        .order('created_at', { ascending: false })
        .limit(1000);
      
      if (error) throw error;
      return data as Transaction[];
    },
  });

  const applyPreset = (preset: 'last7' | 'last30' | 'thisMonth') => {
    const now = new Date();
    switch (preset) {
      case 'last7':
        setDateRange({ from: subDays(now, 7), to: now });
        break;
      case 'last30':
        setDateRange({ from: subDays(now, 30), to: now });
        break;
      case 'thisMonth':
        setDateRange({ from: startOfMonth(now), to: now });
        break;
    }
  };

  const exportToCSV = () => {
    if (!transactions || transactions.length === 0) {
      toast.error('No transactions to export');
      return;
    }

    const headers = ['Date', 'User ID', 'Type', 'Amount', 'Balance After', 'Description', 'Model Used'];
    const rows = transactions.map(t => [
      format(new Date(t.created_at), 'yyyy-MM-dd HH:mm:ss'),
      t.user_id,
      t.transaction_type,
      t.amount.toFixed(2),
      t.balance_after.toFixed(2),
      t.description || '',
      t.model_used || ''
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `billing-transactions-${format(new Date(), 'yyyy-MM-dd')}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    toast.success('CSV exported successfully');
  };

  const exportToPDF = () => {
    if (!transactions || transactions.length === 0) {
      toast.error('No transactions to export');
      return;
    }

    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(0, 113, 227);
    doc.rect(0, 0, 210, 30, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Billing Transactions Report', 20, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(format(new Date(), 'PPP'), 20, 26);

    // Table
    const tableData = transactions.map(t => [
      format(new Date(t.created_at), 'yyyy-MM-dd HH:mm'),
      t.user_id.substring(0, 8) + '...',
      t.transaction_type,
      `$${t.amount.toFixed(2)}`,
      `$${t.balance_after.toFixed(2)}`,
      t.description || '-',
      t.model_used || '-'
    ]);

    doc.autoTable({
      startY: 40,
      head: [['Date', 'User ID', 'Type', 'Amount', 'Balance', 'Description', 'Model']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [0, 113, 227], textColor: 255 },
      styles: { fontSize: 8, cellPadding: 2 },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 25 },
        2: { cellWidth: 25 },
        3: { cellWidth: 20 },
        4: { cellWidth: 20 },
        5: { cellWidth: 35 },
        6: { cellWidth: 25 }
      }
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Page ${i} of ${pageCount} | Generated by Genau Admin`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
    }

    doc.save(`billing-transactions-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
    toast.success('PDF exported successfully');
  };

  return (
    <Card className="border-[#E5E5EA]">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg font-semibold text-[#111111]">
              Transaction History
            </CardTitle>
            <CardDescription>
              Organization-wide billing transactions
            </CardDescription>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-2 mr-2">
              <Button
                onClick={() => applyPreset('last7')}
                variant="outline"
                size="sm"
                className="border-[#E5E5EA]"
              >
                Last 7 Days
              </Button>
              <Button
                onClick={() => applyPreset('last30')}
                variant="outline"
                size="sm"
                className="border-[#E5E5EA]"
              >
                Last 30 Days
              </Button>
              <Button
                onClick={() => applyPreset('thisMonth')}
                variant="outline"
                size="sm"
                className="border-[#E5E5EA]"
              >
                This Month
              </Button>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-[#E5E5EA] min-w-[240px] justify-start"
                  >
                    <CalendarIcon className="w-4 h-4 mr-2" />
                    {format(dateRange.from, "MMM d, yyyy")} - {format(dateRange.to, "MMM d, yyyy")}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="end">
                  <div className="p-4 space-y-4">
                    <div>
                      <label className="text-sm font-medium">From</label>
                      <Calendar
                        mode="single"
                        selected={dateRange.from}
                        onSelect={(date) => date && setDateRange(prev => ({ ...prev, from: date }))}
                        className={cn("p-3 pointer-events-auto")}
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">To</label>
                      <Calendar
                        mode="single"
                        selected={dateRange.to}
                        onSelect={(date) => date && setDateRange(prev => ({ ...prev, to: date }))}
                        className={cn("p-3 pointer-events-auto")}
                      />
                    </div>
                  </div>
                </PopoverContent>
              </Popover>
            </div>
            <Button
              onClick={exportToCSV}
              variant="outline"
              size="sm"
              className="border-[#E5E5EA]"
            >
              <FileText className="w-4 h-4 mr-2" />
              Export CSV
            </Button>
            <Button
              onClick={exportToPDF}
              variant="outline"
              size="sm"
              className="border-[#E5E5EA]"
            >
              <FileDown className="w-4 h-4 mr-2" />
              Export PDF
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="text-center py-8 text-[#86868B]">Loading transactions...</div>
        ) : !transactions || transactions.length === 0 ? (
          <div className="text-center py-8 text-[#86868B]">No transactions found</div>
        ) : (
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>User ID</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Balance After</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead>Model</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {transactions.map((transaction) => (
                  <TableRow key={transaction.id}>
                    <TableCell className="font-mono text-xs">
                      {format(new Date(transaction.created_at), 'MMM d, yyyy HH:mm')}
                    </TableCell>
                    <TableCell className="font-mono text-xs">
                      {transaction.user_id.substring(0, 8)}...
                    </TableCell>
                    <TableCell>
                      <Badge 
                        variant={transaction.transaction_type === 'credit' ? 'default' : 'secondary'}
                        className="text-xs"
                      >
                        {transaction.transaction_type}
                      </Badge>
                    </TableCell>
                    <TableCell className={`font-semibold ${
                      transaction.amount > 0 ? 'text-green-600' : 'text-red-600'
                    }`}>
                      {transaction.amount > 0 ? '+' : ''}${transaction.amount.toFixed(2)}
                    </TableCell>
                    <TableCell className="font-mono text-xs">
                      ${transaction.balance_after.toFixed(2)}
                    </TableCell>
                    <TableCell className="text-xs text-[#86868B] max-w-[200px] truncate">
                      {transaction.description || '-'}
                    </TableCell>
                    <TableCell className="font-mono text-xs">
                      {transaction.model_used || '-'}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
