import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Upload, Image as ImageIcon } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

export const BrandingSettingsTab = () => {
  const [logoUrl, setLogoUrl] = useState("");
  const [reportTitle, setReportTitle] = useState("Audit Report");
  const [reportFooter, setReportFooter] = useState("Generated by AI");
  const [primaryColor, setPrimaryColor] = useState("#0071E3");
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  useEffect(() => {
    fetchBranding();
  }, []);

  const fetchBranding = async () => {
    setIsLoading(true);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    const { data, error } = await supabase
      .from('user_branding')
      .select('*')
      .eq('user_id', user.id)
      .single();

    if (data) {
      setLogoUrl(data.logo_url || "");
      setReportTitle(data.report_title || "Audit Report");
      setReportFooter(data.report_footer || "Generated by AI");
      setPrimaryColor(data.primary_color || "#0071E3");
    }

    setIsLoading(false);
  };

  const handleLogoUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    setIsLoading(true);

    try {
      const fileName = `${user.id}/logo-${Date.now()}.${file.name.split('.').pop()}`;
      
      const { data: uploadData, error: uploadError } = await supabase.storage
        .from('knowledge-base')
        .upload(fileName, file);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('knowledge-base')
        .getPublicUrl(uploadData.path);

      setLogoUrl(publicUrl);
      
      toast({
        title: "Logo uploaded",
        description: "Click Save Changes to apply your new logo",
      });
    } catch (error) {
      console.error('Logo upload error:', error);
      toast({
        title: "Upload failed",
        description: error instanceof Error ? error.message : "Failed to upload logo",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    setIsSaving(true);

    const { error } = await supabase
      .from('user_branding')
      .upsert({
        user_id: user.id,
        logo_url: logoUrl,
        report_title: reportTitle,
        report_footer: reportFooter,
        primary_color: primaryColor,
      });

    if (error) {
      toast({
        title: "Failed to save branding",
        description: error.message,
        variant: "destructive",
      });
      setIsSaving(false);
      return;
    }

    toast({
      title: "Branding saved",
      description: "Your custom branding will appear in future PDF exports",
    });
    setIsSaving(false);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>White-Label Branding</CardTitle>
          <CardDescription>
            Customize audit reports with your logo and branding (Agency plan only)
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Logo Upload */}
          <div className="space-y-2">
            <Label>Custom Logo</Label>
            <div className="flex items-center gap-4">
              {logoUrl && (
                <div className="w-32 h-32 border-2 border-border rounded-lg flex items-center justify-center bg-muted overflow-hidden">
                  <img src={logoUrl} alt="Logo preview" className="max-w-full max-h-full object-contain" />
                </div>
              )}
              <div className="flex-1">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleLogoUpload}
                  className="hidden"
                />
                <Button 
                  variant="outline" 
                  onClick={() => fileInputRef.current?.click()}
                  disabled={isLoading}
                >
                  <Upload className="w-4 h-4 mr-2" />
                  Upload Logo
                </Button>
                <p className="text-xs text-muted-foreground mt-2">
                  Recommended: 512x512px PNG with transparent background
                </p>
              </div>
            </div>
          </div>

          {/* Report Title */}
          <div className="space-y-2">
            <Label htmlFor="report-title">Report Title</Label>
            <Input
              id="report-title"
              placeholder="Audit Report"
              value={reportTitle}
              onChange={(e) => setReportTitle(e.target.value)}
              maxLength={50}
            />
            <p className="text-xs text-muted-foreground">
              This will appear at the top of PDF exports (max 50 characters)
            </p>
          </div>

          {/* Report Footer */}
          <div className="space-y-2">
            <Label htmlFor="report-footer">Report Footer</Label>
            <Input
              id="report-footer"
              placeholder="Generated by AI"
              value={reportFooter}
              onChange={(e) => setReportFooter(e.target.value)}
              maxLength={100}
            />
            <p className="text-xs text-muted-foreground">
              Footer text at the bottom of each page (max 100 characters)
            </p>
          </div>

          {/* Primary Color */}
          <div className="space-y-2">
            <Label htmlFor="primary-color">Primary Accent Color</Label>
            <div className="flex items-center gap-4">
              <Input
                id="primary-color"
                type="color"
                value={primaryColor}
                onChange={(e) => setPrimaryColor(e.target.value)}
                className="w-20 h-10"
              />
              <Input
                type="text"
                value={primaryColor}
                onChange={(e) => setPrimaryColor(e.target.value)}
                placeholder="#0071E3"
                className="flex-1"
              />
            </div>
          </div>

          {/* Preview */}
          <div className="border-2 border-border rounded-lg p-6 bg-muted/30">
            <h4 className="text-sm font-semibold mb-4">Preview</h4>
            <div className="bg-card border border-border rounded-lg overflow-hidden">
              <div 
                className="px-6 py-4 text-white"
                style={{ backgroundColor: primaryColor }}
              >
                <h3 className="font-bold text-lg">{reportTitle || "Audit Report"}</h3>
              </div>
              <div className="p-6">
                <p className="text-sm text-muted-foreground">Sample audit content...</p>
              </div>
              <div className="px-6 py-3 border-t border-border text-center">
                <p className="text-xs text-muted-foreground">{reportFooter || "Generated by AI"}</p>
              </div>
            </div>
          </div>

          <Button onClick={handleSave} disabled={isSaving}>
            {isSaving ? "Saving..." : "Save Changes"}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
};
