-- Feature 3: Team Management - Organizations and team members tables
CREATE TABLE public.organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  owner_id UUID NOT NULL,
  subscription_tier TEXT DEFAULT 'team',
  max_members INTEGER DEFAULT 5,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.team_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id UUID,
  role TEXT DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member')),
  invited_email TEXT,
  invite_status TEXT DEFAULT 'pending' CHECK (invite_status IN ('pending', 'accepted', 'declined')),
  invited_at TIMESTAMPTZ DEFAULT now(),
  joined_at TIMESTAMPTZ,
  UNIQUE(organization_id, user_id)
);

-- Add organization_id to existing tables
ALTER TABLE public.user_usage ADD COLUMN organization_id UUID REFERENCES public.organizations(id);
ALTER TABLE public.conversations ADD COLUMN organization_id UUID REFERENCES public.organizations(id);

-- Feature 4: White-Label Reports - User branding settings table
CREATE TABLE public.user_branding (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE,
  logo_url TEXT,
  report_title TEXT DEFAULT 'Audit Report',
  report_footer TEXT DEFAULT 'Generated by AI',
  primary_color TEXT DEFAULT '#0071E3',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Feature 5: Project Folders - Folders table and folder_id for conversations
CREATE TABLE public.project_folders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  color TEXT DEFAULT '#0071E3',
  icon TEXT DEFAULT 'folder',
  position INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.conversations 
ADD COLUMN folder_id UUID REFERENCES public.project_folders(id) ON DELETE SET NULL;

-- Enable RLS on new tables
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_branding ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_folders ENABLE ROW LEVEL SECURITY;

-- RLS Policies for organizations
CREATE POLICY "Users can view their own organizations" ON public.organizations
  FOR SELECT USING (owner_id = auth.uid() OR id IN (
    SELECT organization_id FROM public.team_members WHERE user_id = auth.uid()
  ));

CREATE POLICY "Owners can update their organizations" ON public.organizations
  FOR UPDATE USING (owner_id = auth.uid());

CREATE POLICY "Owners can insert organizations" ON public.organizations
  FOR INSERT WITH CHECK (owner_id = auth.uid());

-- RLS Policies for team_members
CREATE POLICY "Org members can view team" ON public.team_members
  FOR SELECT USING (
    organization_id IN (SELECT id FROM public.organizations WHERE owner_id = auth.uid())
    OR user_id = auth.uid()
  );

CREATE POLICY "Org owners can manage team" ON public.team_members
  FOR ALL USING (
    organization_id IN (SELECT id FROM public.organizations WHERE owner_id = auth.uid())
  );

-- RLS Policies for user_branding
CREATE POLICY "Users can manage own branding" ON public.user_branding
  FOR ALL USING (auth.uid() = user_id);

-- RLS Policies for project_folders
CREATE POLICY "Users can manage own folders" ON public.project_folders
  FOR ALL USING (auth.uid() = user_id);